= Kurze Beschreibung der Ziele, Aktivitäten und Ergebnisse in den OpenUP-Projektphasen / Iterationen

== Inception Phase Anfangsphase
===  Hauptaktivitäten

Unsere Hauptaktivität bestand darin das wir die Webanwendung so gut es geht vollumfänglich Implimentieren können.  Da wir nicht auf ein bestehendes System aufsetzen beziungsweise weiterentwickeln gab es einige Herausvorderungen denen Wir uns als Gruppe stellen mussten. 

* Auswahl der Anwendungsart = Webanwendung
* Auswahl der dafür verfügbaren Techniken = HTML, etc.
* Beschaffung der Hardware vom StuRa = Hat geklappt aber sehr spät
* Auschließliche Verwendung von Open Source Lizenzen

==== Anforderungserhebung und -analyse

Der StuRa vorderte von uns ein Tool mit welchen User unbestimmter Art, meistens aber Professoren und HTW Studeten, verschiedene Arten von Anträgen beim StuRa der HTW-Dresden einreichen können. Das sollte sehr einfach funktionieren so das die Bedinung leicht ist und gut verständlich ist. Desweiteren soll das zu entwickelnde Tool auch die möglichkeit haben die verschieden eingereichten Anträge wieder in einer Listenform anzuzeigen. Zudem soll eine Bearbeitungs möglichkeit für StuRa Mitglieder geschaffen werden. Also ein Tool für das Einrechen und Bearbeiten von StuRa Anträgen war gefordert.

Nach dem Esten Kundengespräch im neuen Semester überprüften wir nocheinmal unseren wissenstand und Fragten nach Änderungen.

[cols=2*,options=header]
|===

|Problemstellung
|Analyse

|Einfache Bedinbarkeit
|Verwendung von HTML Formularen

|verschiedene Antragsarten
|die verschiedenen Antragsarten die der StuRa implementiert haben möchte erkennen und von Antragsformularen für die Händische Ausfüllung in einfache HTML Formulare umwandeln

|Ausgabe der eingereichten Anträge in Listenform
|Eigene HTML seite die als Übersicht der Einzelen Anträge dienen soll 

|Bearbeitungs möglichkeit für StuRa Mitglieder
|Verwendung eines Login systems der Verschiedene Funktionen sperrt oder zugänlich macht

|Bearbeitung der eingereichten Anträge
|

|===

== Elaboration Phase Ausarbeitungsphase

=== Hautpaktivitäten
==== Anforderungserhebung und -analyse

Nach der Groben Richtung und der Erörterung der Domäne, sowie des Fachlichen Problems der Aufgabenstellung, führten wir Zahlreiche Meetings mit den Auftraggebern durch. Hier 

== Construction Phase Konstruktionsphase

== Transition Phase Übergangsphase

== Entwurf

== Implementierung

== Test

== Übergabe und Dokumentation

= Welche Entscheidungen wurden getroffen? Warum?

= Was hat gut geklappt, was nicht? 

== Welche Ursachen gab es dafür?

= Wie wurde mit Problemen umgegangen? 

== Haben die getroffenen Maßnahmen gewirkt?
