= Kurze Beschreibung der Ziele, Aktivitäten und Ergebnisse in den OpenUP-Projektphasen / Iterationen

== Inception Phase Anfangsphase
===  Hauptaktivitäten

Unsere Hauptaktivität bestand darin das wir die Webanwendung so gut es geht vollumfänglich Implimentieren können.  Da wir nicht auf ein bestehendes System aufsetzen beziungsweise weiterentwickeln gab es einige Herausvorderungen denen Wir uns als Gruppe stellen mussten. 

* Auswahl der Anwendungsart = Webanwendung
* Auswahl der dafür verfügbaren Techniken = HTML, etc.
* Beschaffung der Hardware vom StuRa = Hat geklappt aber sehr spät
* Auschließliche Verwendung von Open Source Lizenzen

==== Anforderungserhebung und -analyse

Der StuRa vorderte von uns ein Tool mit welchen User unbestimmter Art, meistens aber Professoren und HTW Studeten, verschiedene Arten von Anträgen beim StuRa der HTW-Dresden einreichen können. Das sollte sehr einfach funktionieren so das die Bedinung leicht ist und gut verständlich ist. Desweiteren soll das zu entwickelnde Tool auch die möglichkeit haben die verschieden eingereichten Anträge wieder in einer Listenform anzuzeigen. Zudem soll eine Bearbeitungs möglichkeit für StuRa Mitglieder geschaffen werden. Also ein Tool für das Einrechen und Bearbeiten von StuRa Anträgen war gefordert.

Nach dem esten Kundengespräch im neuen Semester überprüften wir nocheinmal unseren Wissenstand und fragten nach Änderungen.

[cols=2*,options=header]
|===

|Problemstellung
|Analyse

|Einfache Bedinbarkeit
|Verwendung von HTML Formularen

|Verschiedene Antragsarten
|Die verschiedenen Antragsarten die der StuRa implementiert haben möchte erkennen und von Antragsformularen für die Händische Ausfüllung in einfache HTML Formulare umwandeln

|Ausgabe der eingereichten Anträge in Listenform
|Eigene HTML seite die als Übersicht der Einzelen Anträge dienen soll 

|Bearbeitungs möglichkeit für StuRa Mitglieder
|Verwendung eines Login systems der Verschiedene Funktionen sperrt oder zugänlich macht

|Bearbeitung der eingereichten Anträge
|StuRa eigendes Formular für die Bearbeitung der jeweiligen Anträge zuzüglich der Elemente für die Beschlussfassung des StuRas

|Open Source Lizenzen verwenden
|Nur auf Open Source Frameworks, etc. zurückgreifen

|===

== Elaboration Phase Ausarbeitungsphase (RDK)

=== Hautpaktivitäten
==== Anforderungserhebung und -analyse

Nach der Groben Richtung und der Erörterung der Domäne, sowie des Fachlichen Problems der Aufgabenstellung, führten wir Zahlreiche Meetings mit den Auftraggebern durch. Hier haben wir den Fokus auf alle möglichen Uses-Cases der Anwendung gelegt. Aufbauend auf diesem Wissen, haben wir die ersten Use-Case-Diagramme erarbeitet und begonnen das Use-Case-Modell anzufertigen. Dies hat uns am eher viele Probleme bereitet. Leider war das einarbeiten in die Prozesse des StuRa sehr anstrengend und zeitintensiv. Da es sich beim StuRa um eine Einrichtung mit sehr hohem Aufwand an förmlich einzuhaltenen Regeln. Hier gibt es viele Punkte die beachtet werden müssen welche für uns vollumfänglich kaum zu verstehen waren. Hier hatten wir viele Nachfragen bei jedem Meeting mit den Themenstellern bis wir die ganze Domäne vollumfänglich verstanden hatten.


==== Entwurf

Im Entwurf haben wir begonnen zu Planen in welche Richtung wir technisch gehen wollen. Hier haben wir den Fokus auf zu nutzen Technologien gelegt. Wir haben uns informiert welche Komponenten für unser System als Webanwendung nötig sind. In dieser Phase hat sich herauskristalisiert das wir einen Webserver benötigen. Die Lösung zur Haltung der Daten erschien ist erst als txt Dateien sinnvoll. Wir behielten uns jedoch eine Datenbanklösung im Hinterkopf.

Wir befassten uns außerdem welche einzelnen Komponenten des Systems notwendig sein sollten. Wir arbeiteten aufgrund der Analyse heraus, das wir Funktionalitäten zum Einfügen und zum Anzeigen von Anträgen bereitstellen müssen. Mit diesem Wissen planten wir ebenfalls die Kommunkation mit dem Webserver und den bis jetzt vorhandenen Datenstrukturen.

Außerdem haben wir abgeklärt welche Programmiersprachen bzw. welche Sprachen generell für einen Webservice benötigt werden. Hier haben wir uns auf die im Frontend dominanten Sprachen: HTML / CSS / JavaScript geeinigt. Hier hatte Herr Müller bereits ein kleines Konzept im Kopf, welches Design und welche Stuktur die Webseite haben sollte. Da wir im Backend eine möglichst gut verständliche Sprache nutzen sollten, haben wir uns auch aufgrund von Vorkentnisse auf Python geeinigt. jedoch schien es alles deutlich einfacher als es am Ende war. Hier plante wir die erste Kommunikation mit der Datenbank, welche über einfache Scripte abfolgen sollte. Der Plan sah vor das wir in SQL Abfragen formulieren wollten, welche wir dann in die Anwednung übernehmen wollten. Datrauf aufbauend befasste sich Herr Kraus, da er Vorwissen in Python hatte, mit dem Backend Part und den damit verbundenen Möglichkeiten der Umsetzung. Da wir es hier möglichst einfach halten wollten, wollten wir zunächst auf ein Framework verzichten und planten zuerst nur mit wenigen Bibliotheken und einfachen Skipten.



Zusätzlich planten wir erste Versionen des Webservers und beschäftigten uns mit der groben Infrastruktur im StuRa. Hier haben wir uns angeeignet, wie ein Webserver einzurichten ist und Erfahren wie dieser im StuRa bereitgestellt wird.

==== Implementierung

Hier gab ein Teammitglied einen Einstieg in HTML als mit größte Komponente des Frontends. Da das Teammitglied schon Erfahrungen mit Frontend-Sprachen hatte, konnte er uns in diesem Fall viel Wissen vermitteln und uns alle anfallenden Fragen bereits erklären. Danach haben wir uns alle mit den geplanten Technologien auseinandergesetzt, aber gemerkt, dass ohne konkretes Ziel ein Anwenden der Sprachen kaum sinnvoll war. Es schien uns am sinnvollsten Herr Müller (mit den Erfahrungen im Frontend) für slbigen Part einzusetzen. Wir hatten hier vorerst eine unterstützende Funktion.
Dabei wurde bereits eine erste Demo Version von Herr Müller erstellt. Hier haben wir uns ein gewisses Konzept für das Frontend überlegt, um einerseits eine gewisse Einheitlichkeit zu bekommen und um das Frontend ebenfalls nach einem Plan entwickeln zu können.
Da das Feedback zum Größtenteil positiv war, wurde die Demo Version weiterverfolgt.

Im Backend fehlte uns leider das nötige Wissen um die einsetzbaren Technologien möglichst gut abzuschätzen. Es wurden mit Python erste Scripte, die CRUD Operationen ausführen sollen, zu planen / zu erstellen. Die Scripte bauten auf den HTML Dateien der Demo auf und sollten den input der HTML Forms entgegennehmen und in die Dtaenbank schreiben.

==== Test

Es wurden bereits erste Testfälle für die Demo geplant. Leider begrenzte sich das ganze nur auf einzelne Dummy clicks ohne Funktion da wir weder einen Webserver, noch eine Datenbank online zur verfügen hatten. Hier haben wir versucht das ganze lokal über Container zu betreiben.

==== Dokumentation

=== Implementierung

* Jet Brains
** PHP Storm
** PyCharm
* MySQL
** Das verwendete Tool
* VM-ware Player
* Internetbrowser
** Google Chrome (V. 91.0.4472.114)
** Safari (V. 14.0.3)
** Microsoft Edge (V. 91.0.864.59)
** Mozilla Firefox (V. 89.0.2)

Als Entwicklungstool für die Webanwendung im Frontend wurde anfangs Jet Brains PHP Storm mit der Sudenten Lizenz verwendet da dieses Tool einige sehr nützliche Features mitbrachte wie die eien Projektexplorer eine Implementierung von Git was die Dateiverwaltung sehr einfach gestaltete sowie einen Tool eigenen Browser der die HTML Seiten korrekt darstellen kann dies machte es möglich live Änderungen am HTML, CSS code vorzunehmen und dierekt ein Ergebniss zu sehen ohne erst eine Browsereite neu laden zu müssen. Das ist eine Eigenschaft des Programm die ich (Richard Müller) sehr schätze.

Die erste Version der Webanwendung beschrieb nur die Grafische Oberfläche für den Endbenutzer ohne ein Backend. Diese Version wurde mit dem Kunden regelmäßig abgestimmt und nach seinen Wünschen und Vorstellungen erweitert und Angepasst.

Bei der Implementierung der Backend Lösung stießen wir auf etliche Probleme. Die erste geplante Version des Tools sah vor das eingereichte Formulare als Textdateien auf dem Server abgespeichert werden. Mit dieser Lösung wollten wir auf eine Datenbank verzichten, da in unseren Augen eine Datenbank zu viele Funktionen hat die Wir nicht benötigen. Da allerdigs der Aufwand eine Textdatei mit den Inputs eines HTML Formulars zu erstellen, abzuspeichern und dann wieder in ein HTML Formular einzulesen viel zu umständlich war entschlossen wir uns kurzfristig auf eine MySQL Datenbank umzuswitchen da so die Datenspeicherung über eine Tabellenverwaltung deutlich vereinfacht wurde und eine bessere übersicht der Daten ermöglichte.

Das Einrichten der Datenbank geschah über eine lokale MySQL Server installation die erst in einer Virtuellen umgebung und dann später auf dem "echten" Server des StuRas installiert wurde. 

Von einem Problem in das nächste. Die Datenbank lief für sich und die HTML seite lief für sich aber es gab keine Möglichkeit diese Sinnvoll zu verbinden. Der este plan Sah vor das nach unserer Entscheidung für Python unger zu Hilfe nahme von PHP scripten als "Auslöser" die Input Daten aus den Formularen mittels "insert" Anweisungen in die Datenbank geschrieben werden sollten. Dies war nicht möglich da der verwendete Webserver Apache PHP scripte nicht ausführt. Auch nach mehrfacher Konfiguration des Webservers weigerte er sich immernoch die schripte ordnungsgemäß oder überhaubt auszuführen.

Da wir uns am anfang des Semesters gegen ein Web Framework, da keines der Teammitglieder Erfahrungen mit dem Arbeiten mit Web Frameworks hat, oder einen HTML Bauskasten etc. entschieden hatten mussten wir einsehen das wir mit unserer Lösung nicht weiterkahmen. Daraufhin Entschlossen Wir das die Webanwendung auf das Django Framework umgebaut werden muss. Dies bereitete einige Probleme da sich das Implementierungs-Team erst auf das Framework einarbeiten musste und dann die Frontend Lösung umschreiben musste, dies hat einiges an Zeit beansprucht. Die Syntax für das inlcuden von externe CSS und Java Script Files war eine andere als im herkömmlichen HTML verwendet da das Framework eine eigene File und Arbeitsstruktur mitbrachte.

Der Umbau erfolgte zuerst nur im Backend, so dass es erstmal kleine Tests im neuen Framework gab. Der Vorteil von Django war hier ganz klar, dass eine Kommunikation mit der Datenbank nicht selbst geschehen muss. Hier wird alles direkt ovm Framework verwaltet und unser Problem mit der Datenbank wurde gelöst.

Django brachte aber noch mehr Vorteile und möglickeiten mit die wir so gut es möglich war versuchten für unsere Zwecke auszuschöpfen. Wir verwarfen die idee mit PHP srcripten und stellten unsere Kommunikation auf pures Python um da Django ein in Python geschriebenes Framework ist. Damit konnten wir die Formulare einfach anhand der input/textarea/selects namen/values auslesen und in die Datenbak schreiben.

Parallel dazu wurde an einer Login lösung gearbeitet. Die erste herangehenweise war eine htaccess datei als login- und sicherheislösung zu verwenden da der geplante Haubtwebserver Apache war. Allerdings war dies nicht möglich da die htaccess datei nicht ohne weiteres mit Django kompartiebel war und somit ein Datenaustausch von login informationen erschwert wurde. Lösung des ganzen war die Erstellung einer eigenen Loginpage der Frontanwendung. 

Django bot eine eigene Andmin Seite an die mit diversen Funktionen ausgestatet is wie das erstllen und bearbeiten von Bemutzern oder das Auslesen und Manipulieren der Datenbak tablellen.  Dies macht die vorherige Entwicklung und Einbettung einer eigenen Adminseite überflüssig. Zudem ist die Django interne Seite mit einigen Sicherheits features ausgestattet die bei der eingenen Lösung nur schwer bis garnicht Implementiert werden könnte. Darunter fällt beispielsweise die unterscheidung zwischen normalen Benutzer und Administrator da nur ein Admin die Admin seite aufrufen können soll.

Da unser StuRa Server troz mehrfacher nachfrage beim StuRa auf sich warten lies mussten wir Kreativ werden für die weitere Implemtierung. Dazu schafften wir eine lokale installation unserer Einzelen lösungen. Konkret wurde eine Linux VM mit Ubuntu aufgesetzt mit der ein MySQL Datenbankserver betrieben wurde. Jet Brains PyCharm brachte die Django Framework serverinstans mit mit der es möglich war unter localhost ein Server zu testen. Mit dieser Spartanischen lösung wurde weiterentwickelt und Debuggt. Das Problem war nur das diese Installation auf einem Privaten Rechner eines Gruppenmitglieds installiert war und so nur eine Person den Code der anderen ausführen konnte. Dies stelle kein großes Problem dar da unser Programm für die Meetings (Discord) die möglickeit anbot live eine Bildschirmübertragung zu starten damit jeder verfolgen konnte was ging und was nicht. 

Mit diesen zum teil immer wiederkehrenden Problemen wurde nun weiter Implementiert, Debuggt und mit dem Kunden abgesprochen bis ca. Mitte Juni der StuRa uns einen Server bereitstellen konnte. Damit konnte die Finale Implementierungsphase sowie die Finalie Installation beginnen. Diese Phase begann auch schon mit dem erstem Problem, der Server wollt das Djangoprojekt nicht ausführen da ein wsgi error ausgab. Dieses Problem wurde mit einem Guide behoben werden konnten. Damit wurde Django und die dazu passende Python instanns in eine Virtuelle umgebung kopiert, installiert und Konfiguriert.

Die Grundlegene Kommunikation sieht vor das der Apache Webserver die Hereinkommenden Anfragen der User Annimmt und an den Djangoserver weiterleitet und umgekehrt das der Webserver die Antwort von Django dem User darstellt. Die schwierigkeit dabei lag daran dem Server einen weiteren Virtuellen host zu konfigurieren sowie die Firewall zu bearbeiten. 

Das installieren des MySQL Servers machte keine Probleme und verlief reibungslos genau so wie das tauschen der Django projekte Fehlerfrei lief. 

Im letzten Schritt der Implemetierungsphase wurden Bugs behoben und der Code aufgeräumt, nicht genutze Scripte und Funktionen entfert oder überarbeitet.

Es wurde für das Starten des Servers sowie das migrieren neuer Daten ein Shellscript geschrieben, welches in den Autostart des Linux Servers gebracht werden sollte. Dies war allerdings nicht Erfolgreich. Das Script welches Problemlos den Server Startet und die daten mirgiert wurde nicht vom Server automatisch im Starup gestartet. Es wurde versucht über eine rc.lokal datei zu starten, nicht erfolgreich. Das Erstellen und aktivieren eines eigenen Services, nicht erfolgreich. Das verwenden einer Crontabelle, nicht erfolgreich. Das Kopieren der Datei in das init.d Verzeichnis mit anschließender Konfiguration, nicht erfolgreich. Da dies keine Anforderung war und nur der einfachen wartbarkeint dienen sollte wurde die Idee verworfen und der Prozess in eine screen session geschickt. Diese muss nach jedem reboot des Serves neu manuell gestartet werden. Der server hat keine automatischen reboot konfiguriert.

== Transition Phase Übergangsphase

Hier schwankte es zwischen Test und Implentierung da hier beide Teams Hand in Hand arbeiten und sich gegenseitung versuchten zu unterstützen. Nachdem Wir unseren Server beim StuRa eingerichtet hatten und die Software aufgespielt hatten. 

== Test

Das Testen wurde hintenangestellt da die Implentierung große schwierigkeiten hatte und somit lange nichts zum Testen vorhanden war. Zum Teil wurde das Testen der Implentieten Funktionen bereit bei der Implentierung übernommen da bei einer Webanwendung mit Datenbank anbindung automatisch beim Coden getestet wird ob alles so funktioniert wie angenommen was natürlich den Testern arbeit abnimmt diese aber auch eine längere Zeit in der Entwicklungsphase "überflüssig" macht. Da die Lokale instanz sich nicht ohne schwierigkeiten kopiert werden konnte, blieb eine Testmöglichkeit lange aus.

Django funktionierte auf den Computern der restlichen Gruppenmitglieder nicht richtig oder ließ sich ganicht starten. Trotz mehrfacher Installations und Konfigurations versuche weigertete sich Django erheblich auf anderen Windows Installationen zu Funktionieren. Desweiteren hatte ein weiteren Teammitglied das Problem das seine Hardware die Virtualliserung im BIOS nicht unterstützte was das ausführen des Datenbank servers in der VM unmöglich machte. Damit war das Test team auf den Server des StuRas angewießen. Dessen Bereitstellung verzögerte sich aber auf mitte Juni.

== Übergabe und Dokumentation

Die geplante Übergabe findet am 7.7.2021 statt. Dieser Terin kommt zu stande da Wir versuchen bis zum Schluss bugs zu beben um das Usererlebnis so angenehm wie möglich zu gestalten. Das Übergabeprotokoll wurde bereits erstellt und wir mit dem Kunden abgeglichen und unterzeichnet.
