= 3.Ergebnisse [RDK,A.G]

== 3.1 Was  waren unsere Ziele? (RDK,A.G)

Am Anfang des Projektes haben wir unsere Ziele  sehr hoch gesteckt und wollten, alle Use-Cases des StuRa umsetzen. Allerding haben wir nur doie Use-Cases für die herkömmliche Verwendung des Tools umsetzen können. Also Anträge stellen, Anträge bearbeiten und #die Möglichkeit bieten eigene Anträge und deren Status (noch in Arbeit, vertagt,beschlossen oder abgelehnte) einsehen zu können. 
 
Außerdem haben wir versucht noch zusätzliche Anforderugen, in Form von Add-Ons aufzunehmen, ein Beispiel hierfür wäre die Idee der Automatischen generierung einer Tagesordnung oder einer verbesserten Druckvorlage für Anträge, praktisch haben wir uns schlussendlich erstmal auf die Hauptanwendung (Unsere Use-Cases) konzentriert.

.Use-Case-Model
[plantuml, "diagrams/use_case_model", svg]
....
include::../../docs/requirements/diagrams/use_case_model.puml[]
....

== 3.2 Was haben wir davon Geschafft? (RDK,A.G)

Unser Tool bietet die Möglichkeit Anträge aller gewünschten Formen durch externe und interne Stellen einzureichen. Hier werden die Anträge mit ihren Pflicht Daten vom System verarbeitet und entsprechend nach ihren zuvor modellierten Attributen gespeichert. Diese Speicherung erfolgt permanent. Wir haben ebenfalls geschafft eine Antragsnummer  basierend auf  Jahr( der Legislaturperiode) und Nummer (der nächsten Plenumssitzung) zu  generieren und diese als Antragsnummer abzubilden. Dabei haben wir nach Vorgabe des StuRa eine dynamische Antragsnummer für jeden Antrag generiert, dies wurde zudem ausgiebig getest und funktioniert nach unserem Stand ohne Fehler. 

Eine weitere implementierte Funktionalität des Tools, stellt die Bearbeitung der Anträge dar. Hier haben wir die Möglichkeit geschaffen, einzelne Anträge gezielt auszuwählen und dann durch einen auhorisierten Nutzer bearbeiten zu lassen. Hier bekommt der StuRa ebenfalls die Möglichkeit die Beschlüsse des Antrags direkt einzutragen und falsche Angaben zu korrigieren. 

Zusätzlich lässt sich vom Tool auch eine Liste anzeigen, diese Liste gibt entweder alle Anträge aus oder filltert die Anträge nach Stelle. Durch die Farbe des Hyperlinks kann man erkennen welche Anträge schon eingeshen wurden und welche noch nicht eingeshen wurden . Darauf aufbauend lassen sich mit den Hyperlinks der Antragsnummer, die gestellten Anträge ebenfalls anzeigen bzw. führen zur Bearbeitung. Der nächste Schritt wäre hier den Status des Antrags anzeigen zu lassen dies ist jedoch nicht implementiert (Dies behandelt Use-Case 7 und 8).

Außerdem bietet das Tool die Möglichkeit eines Logins. Hier war unser Ziel für die Nutzer des "Präsidiums" Benutzer-Logins einzurichten, damit ausschließlich diese Zugang zu den Anträgen im Tool bekommen. Wir haben es geschafft das nur verifizierte Nutzer Anträge ansehen und bearbeiten dürfen. Auch durch Angabe von URLs zu Anträgen ist ohne Login keine Anzeige möglich. 

Zusätzlich zu diesem Login gibt es eine Administrationsseite zum tieferen Verwalten der Anträge. Hier können die Datenstrukturen, über die normale Eingabemaske hinaus, ergänzt / geändert / entfernt werden.

Des weiteren haben wir es geschafft, das die ganze Seite einem gewissen Konzept folgt. Wir hatten das Ziel die Benutzung der Seite möglichst einfach und so modern wie möglich zu halten. Dabei stand stets der Nutzer im Vordergrund. Es sollte erreicht werden, dass obwohl bei den Anträgen sehr komplexe Gegebenheiten gelten, eine einfache Nutzung des Tools ohne recherche notwendig ist. #Dies haben wir durch erklärende Texte und Popups zumindest bei unserem kleinen User-Test erreicht.

Zusammengefasst haben wir die Use-Cases 01,02,05 sowie 06 implementiert und getestet. Diese werden  innerhalb unseres Tools in der nächsten Woche 5-11.Juli offiziell übergeben, inoffiziell stehen diese auf dem StuRa-Server schon zur Verfügung.

== 3.3 Was haben wir nicht erreicht? (A.G,RDK)

=== 3.3.1 Störfaktoren

Leider konnten wir einige Funktionalitäten innerhalb des Projektes nicht umsetzen.
Hier ist als großer Faktor der Zeitdruck zu sehen. Dadurch das wir relativ spät im Projekt auf ein Framework umgestiegen sind, mussten wir uns zuerst darin einarbeiten um die Funktionsweise zu verstehen. Da uns dies relativ viel Zeit kostete, waren wir am Anfang von SE II im Verzug. Da in diese Maßnahmen viel Energie geflossen ist, fehlte diese uns leider an anderen Stellen im Projekt bzw. bei der Bearbeitung gennanter Funktionalitäten. Jedoch lässt sich aber sagen, dass wir hier im Hintergrund vielleicht mehr erreicht haben als wir eigentlich dachten. 

Durch das Framework haben wir eine guten Startpunkt für die weitere Entwicklung geschaffen und weitere Funktionalitäten können ohne große Probleme hinzugefügt werden, das ist zwar das nicht mehr Teil unseres Projektes dennoch eine Art zusätzliche Anforderung welche wir in kooperation mit unserem Kunden beschlossen haben, um die Weiterentwicklung zu ermöglichen und zu fördern UMGESCHRIEBEN. 

Zudem sind die Funktionalitäten die wir umgesetzt haben, auch benutzerfreundlich umgesetzt und wurden von unserem Kunden positiv entgegen genommen bzw. gerne verwendet.

Ein anderer Störenderfaktor war  unsere Kundenumgebung, zusammengefasst haben wir am Anfang des Semesters zum Teil mehrere Wochen auf Anfragen keine Rückmeldung bekommen, dies war störend jedoch nicht Projektgefährdend. Dazu kommt, dass es einen Wechsel von Auftragsteller bzw. Kunden gab welche unterschiedlichen Prioritäten bzw. Ansichten zum Tool hatten, dies wäre sogar förderlich gewesen wenn genannter Wechsel nicht in der Mitte des Semesters passiert wäre.

Das allerdings größte Hindernis im Bezug auf unseren Kunden war, das wir Aufgrund von Misskommunikation und Wechsel im StuRa, erstmal keinen Server hatten und unsere Website selber vorerst auf einem lokal gehostetem Webserver implementieren und testen mussten, dies war möglich aber umständlich. 

Wir hätten wahrscheinlich in der Hinsicht noch mehr auf unsren Kunden zugehen müssen haben, aber nach unserer Meinung eigentlich alles getan um die Kommunikation von unserer Seite aus aufrecht zu halten (E-Mail sowie Discord Nachrichten von mind. 2 Personen). 

=== 3.3.2 Was wurde nicht erreicht

Was haben wir also nicht geschafft ?
Im Hinblick auf unsere Use-Cases haben wir leider einige Dinge nicht erreicht darunter zählen die Use-Cases 03,04,07 und 08. Die größte Funktionalität die nicht erreicht wurde, ist die Wiederspiegelung des Status des Antrags. Da diese sehr komplex und vielseitig ist, haben wir uns dafür entschieden diese vorerst nicht zu implementieren. Leider haben wir bisher keine Möglichkeit gesehen diese im aktuellen Stand des Projektes bei der Antragsbearbeitung unterzubringen. In den Modellen existiert jedoch ein Attribut welches diese abbildet. Erschwerend kam hinzu das durch den Status des Antrags gewisse Abläufe abgebildet bzw. ausgedrückt werden sollten. Dadurch das wir hier nicht die Zeit hatten die Abläufe komplett zu verstehen und diese zu modellieren blieb dieses Feature leider außen vor.

Ebenfalls nicht unterstützt wird das Feature des Einsehens der offenen Anträge durch externe Nutzer. Hier war das Ziel für externe Nutzer einzusehen welche Anträge gerade in Bearbeitung sind und welche bereits abgeschlossen. Dadurch das wir die oben genannte Status anzeige der Anträge ebenfalls nicht abbilden konnten mussten wir dieses Feature ebenfalls weglassen. Erschwerend kam hinzu, das hier bei uns Bedenken im Thema Datenschutz auftraten. Da hier personenebzogene Daten im Antrag abgleget werden (Name, Email, Beantwortung sensibler Fragen) wäre nur ein Ansehen eines einzelnen, selbst gestelten Antrages, sinnvoll. Uns ist in diesem Fall keine gute Lösung in der Projekzeiteingefallen, quasi kurzzeitige Links zum ansehen von Anträgen zu generieren.

Ein Feature das noch verbesserunsgwürdig ist, ist das ansehen von Anträgen im "Intern" Bereich. Hier kann man die Anträge nur ansehen indem man in den Bearbeitungsmodus des Tools wechselt. Man zeigt einen Antrag also an, indem man keine Änderungen im Antrag durchführt. Hier gibt es sicher eine bessere Lösung die Anträge als nicht bearbeitbar anzuzeigen.

Auch das Ablehnen und Vertagen von Anträgen mussten wir weglassen. Besonders beim Vertagen des Antrags spielen wieder die Status der Anträge eine Rolle, welcher nicht implementiert sind. Beim Vertagen wird der Antrag auf eine nächste Sitzung verschoben, was genau die abzubildenden Abläufe im StuRa aufzeigt. Hier hätten wir 1. das Feature des Antraggssatus gebraucht und 2. hätte es durch das Ablehnen einer Antragsnummer Änderung bedarft bzw. hätte man hier auch die Tagesordnung der jeweiligen Sitzung beachten müssen, welche als Add-On ebenfalls nicht umgesetzt wurde. 