== Ergebnisse

=== Reflexion

* Was habe ich gelernt?

Erstens habe ich gelernt, wie man mit anderen Teammitgliedern schnell kommunizieren kann. Wir haben eine Whatsapp-Gruppe und eine Discord-Gruppe erstellt, mit denen wir Nachrichten miteinander schicken und Meeting organisiert haben. Zweitens habe ich gelernt, wie man im Team die Aufgaben teilt. Jeder kann etwas gut. Man muss wissen, was er gut kann und was ihm gefällt, um diese Aufgabe gut zu erledigen. Außerdem habe ich gelernt, dass ich manchmal um Hilfe von den anderen bitten kann, dass sich Mitglieder gegenseitig unterstützen sollen.


* Worauf bin ich stolz?

Ich bin darauf stolz, dass ich die Aufgaben meiner Rolle erledigen konnte. Am Anfang war es schwer, weil ich die Aufgaben nicht so gut kannte. Aber mithilfe der anderen und der Dokumentationen konnte ich sie erledigen.


* Was hat gut funktioniert?

Die Zusammenarbeit zwischen den Teammitgliedern hat gut funktioniert. Obwohl wir uns nicht im Präsenz treffen konnten, haben wir uns regelmäßig getroffen und über die Probleme diskutiert. Die Aufteilung der Aufgaben hat auch gut funktioniert, weil jeder die Aufgaben wählen konnte, die ihn interessiert.


* Was würde ich beim nächsten Projekt anders machen?

Ich würde mich auf die Technologie, die bei der Implementierung genutzt wird, vorbereiten. In diesem Projekt haben wir HTML, CSS und JavaScript genutzt. Ich habe diese Sprachen nicht so gut gekannt, deswegen konnte ich bei der Implementierung nicht viel helfen.
