@startuml "logische Sicht"

node "Django-Applikation" {
    [HTML]
    [View]
        note left of [View] : CRUD, Processes requests
    [CSS]
        note left of [CSS]
            predefined W3 
            and own stylesheet
        end note
    [URL Resolver]
        note left of [URL Resolver] : recieves request by url paths

    [JavaScript] ..> [HTML] : toggles, displays text
    [CSS] ..> [HTML] : styles
    [URL Resolver] --> [View] : redirects request
    [View] ..> [HTML] : renders response to browser
    
    [View] --> database : CRUD-Operations
}

database "MySQL-Datenbank" as database {

}
@enduml