# Generated by Django 3.2.3 on 2021-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atool', '0002_auto_20210602_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorymember',
            name='frg4',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
