# Generated by Django 3.2.4 on 2021-06-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atool', '0003_advisorymember_frg4'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorymember',
            name='beschluss',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='advisorymember',
            name='beschlussgrund',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='advisorymember',
            name='beschlusstext',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='advisorymember',
            name='mehrheit',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='beschluss',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='beschlussgrund',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='beschlusstext',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='mehrheit',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='beschluss',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='beschlussgrund',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='beschlusstext',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='mehrheit',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='universall',
            name='beschluss',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='universall',
            name='beschlussgrund',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='universall',
            name='beschlusstext',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='universall',
            name='mehrheit',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
