= Design: {project-name}
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
{mail}
// Platzhalter für weitere Dokumenten-Attribute


== Allgemeine Informationen

* Anträge in tmp Verzeichnis als .txt solange sie nicht beschlosssen wurden im csv Format
* Zu jedem Antrag einen Ordner mit Antragsnummer und Anlagen ( Dateien )
* Nach Beschluss Überführung in ein pdf / zip
* Prozesse der Bearbeitung (Status) wird durch Flags im Antrag gesetzt (ganz oben)
* Login über Plugin mit neuen Browser-Popup, Zugriffe über Gruppenstruktur im Plugin
* Externe Antragssteller sind zu beachten, bei Wahlantrag sinnvoll
* Ablauf Antrag: Ausfüllen -> php action über submit putton -> führt python script mit input vom Antrag aus -> schreibt neue txt csv / Ordner -> Umwandeln zu pdf nach Beschluss 
* Nav Leiste mit Dropdown Menü "Einreichen für normale Anträge" und "intern" -> Einloggen mit zusätzlichen Funktionen
* TO mit ul und links zu den jeweilige Anträge der TOPs
* Anträge haben Prio Flags für TO