@startuml "logische Sicht"

node "Django-Applikation" {
    [Template Files]
    [View]
        note top of [View] : CRUD, Processes requests
    [CSS Stylesheet]
        note left of [CSS Stylesheet]
            predefined W3 
            and own stylesheet
        end note
    [URL Resolver]
        note top of [URL Resolver] : recieves request by url paths
    [URL Patterns] 
        note top of [URL Patterns] :redirect requests to view
    
    [JavaScript display toggle] ..> [Template Files] : toggles, displays text
    [CSS Stylesheet] ..> [Template Files] : styles
    [URL Resolver] --> [URL Patterns] : check patterns
    [URL Patterns] --> [URL Resolver] : tells matching pattern and view
    [URL Resolver] --> [View] : redirects requests
    [View] ..> [Template Files] : renders response to browser
    
    [View] --> database : CRUD-Operations
}

database "MySQL-Datenbank" as database {

}
@enduml