@startuml "logische Sicht"

node "Webserver" {
    [HTML]
    [Python]
    note left of [Python] : scripts select,insert,delete,update
    [CSS]
    note left of [CSS]
        predefined W3 
        and own stylesheet
    end note
    [JavaScript]
    [CSS] ..> [HTML] : styles
    [HTML] --> [Python] : calls
    
    [Python] --> finance : select,insert,delete,update
    [Python] --> universal : select,insert,delete,update
    [Python] --> advisory_member : select,insert,delete,update
    [Python] --> election : select,insert,delete,update
}

database "MySQL" {
    folder "finance" {
        [finance 1]
        [finance 2]
    }
    folder "universal" {
        [universal 1]
        [universal 2]
    }
    folder "advisory_member" {
        [advisory_member 1]
        [advisory_member 2]
    }
    folder "election" {
        [election 1]
        [election 2]
    }
}

@enduml