@startuml "Level 2 - Container"

skinparam actorStyle awesome

actor Antragssteller <<Person>>
actor Präsidium <<Person>>

component "Antragsverwaltungstool" {
    component [Web-Applikation] <<Container>>
    note right of [Web-Applikation]
        Stellt das graphische Overlay dar, 
        empfängt Nutzereingaben und zeigt Informationen geordnet an
    end note
    [Datenbank] <<Container>>
    note right of [Datenbank]
        Speichert Daten zu Anträgen
        und gibt selbige auf Anfrage zurück
    end note
}

Antragssteller ..> [Web-Applikation] : nutzt (HTTP)
Präsidium ..> [Web-Applikation] : nutzt (HTTP)
[Web-Applikation] ..> [Datenbank] : liest, schreibt, löscht in

@enduml