@startuml "Level 1 - Context"

skinparam actorStyle awesome

actor Antragssteller <<Person>>
actor Präsidium <<Person>>
[Antragsverwaltungstool]
note right of [Antragsverwaltungstool] : Web-Applikation zum Verwalten und Stellen von Anträgen im StuRa

Antragssteller ..> Antragsverwaltungstool : nutzt (HTTP)
Präsidium ..> Antragsverwaltungstool : nutzt (HTTP)

note left of Antragssteller : Ein Nutzer der einen Antrag stellt
note right of Präsidium : Ein Mitlgied im StuRa das Anträge verwalten soll/darf
@enduml

