@startuml "Level 2 - Container"

skinparam actorStyle awesome

actor Antragssteller <<Person>>
actor Präsidium <<Person>>

component "Antragsverwaltungstool" {
    component [Django-Applikation] <<Container>>
    note right of [Django-Applikation]
        Stellt das graphische Overlay dar, 
        empfängt Nutzereingaben und zeigt Informationen geordnet an
    end note
    [Datenbank] <<Container>>
    note right of [Datenbank]
        Speichert Daten zu Anträgen
        und gibt selbige auf Anfrage zurück
    end note
}

Antragssteller ..> [Django-Applikation] : nutzt (HTTP)
Präsidium ..> [Django-Applikation] : nutzt (HTTP)
[Django-Applikation] ..> [Datenbank] : liest, schreibt, löscht in

@enduml