= Glossar: {project-name}
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
{mail}
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die wesentlichen Begriffe aus dem Anwendungsgebiet (Fachdomäne) der I3 Antragverwaltungstool-Systems definiert. Zur besseren Übersichtlichkeit sind Begriffe, Abkürzungen und Datendefinitionen gesondert aufgeführt.

== Begriffe
[%header]
|===
|Begriff|	Definition und Erläuterung|	Synonyme
// |Kommissionierung|Bereitstellung von Waren aus einem Lager entsprechend eines Kundenauftrags|(keine))|
| Änderungsantrag |Formular für die Bearbeitung/Ergänzung/Korrektur eines bereits existierenden und eingereichten Antrages.   |(keine)
|Antrag|Gesuch, Forderung|Anfrage, Anliegen. Forderung|
Antrag (offen)|Antrag, welcher eingereicht wurde, aber noch nicht vollständig vom Präsidium bearbeitet wurde.| offener Antrag|
Antragssteller|Jemand, der einen Antrag stellt.|Bewerber, Kandidat, Interessent|
Antragsverwalter|Person, die für einen Antrag verantwortlich ist, ihn in Ordnung hält und betreut|Administrator, Manager|
Beschluss|[gemeinsam festgelegte] Entscheidung; Ergebnis einer Beratung|Entscheidung, Enschließung, Resolution|
Haushaltsplan|Plan, der der Feststellung und Deckung des Bedarfs an finanziellen Mitteln dient, der zur Erfüllung der staatlichen Aufgaben im Bewilligungszeitraum voraussichtlich notwendig ist. In diesem Fall, die finanzielle Mittel, die dem Stura zur Verfügung stehen. |Finanzplan, Etat|
Hochschule für Technik und Wirtschaft Dresden|Bildungsinstitution mit Fokus auf technische und wirtschaftliche Studiengänge |(keine)|
Plenum |Vollversammlung einer Körperschaft, besonders der Mitglieder eines Parlaments. |Vollversammlung|
Präsidium|Leitendes Gremium einer Versammlung.|Vorsitz, Direktorium, Führerschaft|
Referat|Abteilung einer Behörde als Fachgebiet eines Referenten.|Abteilung, Sektion|
Referatskollegium|Das Referatskollegium ist die Gesamtheit aller Referate.|(keine)|
Referatsleitung|Ein von der Referatsleitung zur Vertretung des Referates im Referatskollegium bestimmtes Mitglied.|(keine)|
Ressourcen|Bestand an Geldmitteln, Geldquelle, auf die jemand zurückgreifen kann. |Bestand, Depot|

Studentenrat|Eine Form der Studierendenvertretung an Hochschulen.|Studierendenrat|
Tagesordnung|Gesamtheit der Themen, die bei einer Sitzung, Versammlung behandelt werden sollen.|Agenda|
Tagesordnungpunkt|Punkt einer Tagesordnung.|(keine)|
vertagen|eine Sitzung o. Ä. ergebnislos abbrechen und eine weitere Sitzung zu einem späteren Zeitpunkt ansetzen|verschieben|
Vorstand der Geschäftsführung|Sprecherinnen und Sprecher sowie Beauftragte die dem Referatskollegium mit beratender Stimme angehören.|Sprecher/innen|
|===


== Abkürzungen und Akronyme
[%header]
|===
|Abkürzung|	Bedeutung|	Erläuterung
//|UP|Unified Process|Vorgehensmodell für die Softwareentwicklung|
|HTW Dresden| Hochschule für Technik und Wirtschaft|Ist eine Fachhochschule in Dresden. |
Stura|Studentinnen- und Studentenrat|Ist das zentrale Organ der Studentinnen- und Studentenschaft, u.a. zur Vertretung dieser.  |
TO|Tagesordnung|Gesamtheit der Themen, die bei einer Sitzung, Versammlung behandelt werden sollen.|
TOP|Tagesordnungspunkt|Ist ein Punkt der Tagesordnung|
UC|Use Case|funktionale Anforderung eines Systems
|===

== Verzeichnis der Datenstrukturen
[%header]
|===
|Bezeichnung|	Definition |	Format | Gültigkeitsregeln | Aliase
|Anmeldedaten|Zusammensetzung von Benutzername und Passwort.|String|Emailadresse muss @-Zeichen und Punkt enthalten.|Login|
|===


