= Vision: I3 Antragsverwaltungstool
Jacob Flaskamp <s81424@htw-dresden.de>; Richard Friese <richard.friese@htw-dresden.de>; Andreas Gröber <andreas.groeber@htw-dresden.de>; Jasmin Henn <jasmin.henn@htw-dresden.de>; Ruben-David Kraus <ruben-david.kraus@htw-dresden.de>; Richard Müller <richard.mueller@htw.dresden.de>; Duy Tien Nguyen <s80287@htw-dresden.de>; Amanda Wer Estrada <amanda.werestrada@htw-dresden.de
{localdatetime}
:toc:
:toc-title: Inhaltsverzeichnis
include::../_includes/default-attributes.inc.adoc[]

// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des I3 Antragsverwaltungstool zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die  Details, wie das I3 Antragsverwaltungstool diese Bedarfe erfüllt, werden in der Use-Case und Supplementary Specification beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das I3 Antragsverwaltungstool, das von Team I3 entwickelt wird. Das System wird es der Stura der HTW Dresden erlauben, Anträge zu verwalten indem Antragsformulare vervollständigt werden und automatisch in die Tagesordung der nächsten Sitzung eingeordnet, um damit einen schnelleren und leichteren Antragsverwaltungsprozess zu erleichtern. Diese browserbasierte Anwendung soll das Problem der Unvollständigkeit der Formulare lösen und der Stura kommunizieren wenn Anträge erstellt werden.

=== Definitionen, Akronyme und Abkürzungen
siehe Glossar <<glossary.adoc#>>

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)

== Positionierung
=== Fachliche Motivation
Der Stura der HTW Dresden verwaltet Antragsformulare noch analog. Wenn Bedürfnisse in den einzelnen Referaten entstehen, müssen die einen Antrag stellen. Das Präsidium wird benachrichtigt und der Antrag bekommt ein Identifizierungsnummer. Dann werden Anträge manuell in der Tagesordnung nach einer bestimmten Priorität eingeordnet um verarbeitet zu werden. Wenn der Antrag nicht in der Sitzung bearbeitet wird, wird es vertagt. Aufgrund dieses Prozesses verliert der Stura den Überblick und manche Anträge werden nicht richtig ausgefüllt, die unerarbeitete Anliegen gehen durcheinander und der Stura wird nicht benachrichtigt wenn ein neues Formular erstellt wird. 
Die angestrebte Verbesserung hat als Ziel die Einführung eines browserbasierten Tools um das Erstellen und Verwaltung von Anträge übersichtlich, einfach und automatisch zu machen.
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.

=== Problem Statement

[cols="1,3"]
|===
|Das Problem |	die unübersichtliche Behandlung der Anträge
|betrifft |	alle Mitglieger des Sturas, das Referatskollegium, das Präsidium sowie Sprecher/innen.
|Die Auswirkung davon ist |	die suboptimale Leistung des Sturas und das langsame Verarbeitung von Anträge 
|eine erfolgreiche Lösung wäre |	eine Anwendung um korrekt ausgefüllten und nummerierten Formulare zu erstellen und  gemäß Priorisierung in der Tagesordung der folgenden Sitzung eingeordnet zu werden.
|===

////
Beispiel

[cols="1,3"]
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft |	Studierende der HTW Dresden
|die Auswirkung davon ist |	umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre |	die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
|Für|	den Sutra der HTW Dresden 
|der|	Anträge für Wahlen und Beschlüsse verwaltet
|Die Lösung ist eine | browserbasierte Anwendung
|Das	| digitales Ausfüllen von Antragsformulare
|Im Gegensatz zur	|manuelle Verwaltung der Anträge
|Unser Produkt|	erstellt Anträge automatisch und verknüpft diese mit der Tagesordung der folgenden Sitzung.
|===


//Beispiel Produkt:
//|===
//|Für|	Studierende der HTW
//|die|	die ihren Studienalltag effizienter organisieren möchten
//|Das Produkt ist eine | mobile App für Smartphones
//|Die 	| für den Nutzer Informationen zum Stundenplan und Noten darstellt
//|Im Gegensatz zu	| Stundenplänen der Website und HIS-Noteneinsicht
//|Unser Produkt| zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
//|===

==	Stakeholder Beschreibungen
===	Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
|Name|	Beschreibung	| Verantwortlichkeiten
|[Benennung des Stakeholder-Typs.]	|[Kurze Beschreibung des Stakeholders.]	|[Fassen Sie die wesentlichen Verantwortlichkeiten des Stakeholder mit Bezug auf das zu entwickelnde System kurz zusammen, d.h. ihr besonderen Interessen. Beispiele: Dieser Stakeholder sorgt dafür, dass das System gewartet wird / dass die angezeigten Daten aktuell sind / überwacht den Projektfortschritt / usw.]
| Mitglieder des Sturas | | 
| Referatskollegium | | 
| Sprecher/innen | | 
| Präsidium | | |

|===

=== Benutzerumgebung
Beschreiben Sie die Arbeitsumgebung des Nutzers. Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.

== Produkt-/Lösungsüberblick
=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.


[%header, cols="4,1,4,1"]
|===
|Bedarf|	Priorität|	Features|	Geplantes Release
|xx|xx|xx|xx
|===


== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
|Anforderung|	Priorität|	Geplantes Release
|xx|xx|xx|
|===
