= Architecture Notebook: {project-name}
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
{mail}


== Zielsetzung
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Einschränkungen sowie Begründungen der wesentlichen Elemente und alle anderen übergreifenden Aspekte des Systems, die das Design und die Implementierung beeinflussen.

== Entwurfsziel und Philosophie 
Das System stellt eine Webanwendung dar, welches das Einreichen sowie das Ver- und Bearbeiten von Anträgen vereinfachen und beschleunigen soll. Die Anwendung ist öffentlich zugänglich und muss daher parallel nutzbar sein. Das System soll von den Studenten der HTW (idR 4000-6000) genutzt werden, kann aber auch von Externen verwendet werden. Hier ist von einer simultanen Nutzung von 10-300 Studierenden auszugehen. Zusätzlich ist eine interne, nicht öffentliche Nutzung durch die Mitglieder des StuRa vorgesehen, um Anträge zu bearbeiten und zu prüfen.

Die Aspekete der Prüfung sowie Bearbeitung von Anträgen sollen technisch abgebildet werden um den Aufwand zu verringern und das Bearbeiten zu beschleunigen. Da die verwendeten Endgeräte und ihre technische Anbindung (Hardware, Software, Eingabetechnik, Bandbreite etc.) nicht bekannt und einheitlich sind, ist diese Software browserbasiert, was sie im weitesten Sinne plattformunabhängig macht. 

Um das Stellen von Anträgen für erstmalige Nutzer zu erleichtern ist eine gute Bedienbarkeit notwendig. Es soll klar erkennbar sein welche Anträge stellbar sind und welche Informationen vom Antragssteller notwendig sind. Diese Bedienbarkeit soll durch eine klare Navigation und genaue möglichst einfache Darstellung der geforderten Informationen realsisiert werden.

Das System ist die erste Version und soll auf lange Zeit im StuRa genutzt werden. Ebenfalls soll Platz für Erweiterungen geboten werden. Vorerst sind keine schnellen Änderungen der Software durch Add-ons oder neue Soft- sowie Hardware zu erwarten, dennoch ist hier eine einfache Erweiterung erstrebenswert.

== Annahmen und Abhängigkeiten 
=== Annahmen
* Der Nutzer besitzt stabile und ausreichende Internetanbindung
* Die Webseite wird beim Nutzer korrekt dargestellt
* Bei Anträgen auf Ressourcen oder zur Wahl als Gremiu im StuRa ist der Antragssteller selbst Mitglied im StuRa
* Um den Antragsstatus anzusehen oder einen Änderungsantrag zu stellen, wurde im Vorhinein bereits ein Antrag gestellt
* Zur Bearbeitung von Anträgen hat sich das Mitglied des StuRa im Tool mit zugewiesenem Login angemeldet
* Server von Rechenzentrum / StuRa
* Alle Technologien Open-Source, kein Closed-Source.

=== Abhängigkeiten
* Da wir einen Server bzw. die nötige Infrastruktur zur Verfügung gestellt bekommen sind wir von der Leistung und Verfügbarkeit des StuRa-Netzwerkes abhängig.

== Architektonisch bedeutende Anforderungen (ergibt sich aus Use-Cases und Furbs+)
=== Functional
*SWFA-1:* Für das Bearbeiten von Anträgen ist ein Login nötig, um sicherzustellen das nur zuständige StuRa-Mitglieder Anträge bearbeiten können.

*SWFA-2:* Das System muss alle Daten der Anträge persistent speichern.

=== Wartbarkeit (Supportability)
*NFAS-1:* Das System soll die Möglichkeit bieten, später eine weitere Sprachen einbinden zu können.

== Entscheidungen, Einschränkungen und Begründungen (Programmiersprachen ,Bibliotheken, Framworks, DBS-Managementsystem usw + Begründung)
. Generell ist nur das Nutzen von Open-Source Software vorgesehen.
. HTML bildet die Grundlage des Aufbaus unserer Webseite.
.  Wir nutzen Javascript, da es in Webapplikationen zur Nutzerinteraktion verbreitet ist & Vorwissen vorhanden ist.
. Ebenfalls findet CSS bei uns Anwendung, da es zum Gestalten der Webseite unverzichtbar ist. Hier bedienen wir uns eines vorgefertigten Stylesheets von W3.
. Um die Nutzereingaben serverseitig zu Bearbeiten, verwenden wir Python als gut verständliche und vielseitige Programmiersprache.
. Als Webserver kommt Apache zum Einsatz, da er weit verbreitet und gut dokumentiert ist.
. Wir verwenden die relationale Datenbank MySQL da wir die Anträge gut als Tabellenstruktur abbilden können.
. Um die vom Nutzer übermittelten Eingaben in einen Datensatz in der Datenbank umzuwandeln, nutzen wir die PyMysql um aus den Eingaben Abfragen auf der Datenbank zu generieren.
. PyMysql bildet für die Datenverarbeitung die Grundlage der Kommunikation zwischen dem Webserver und der Datenbank.

== Architekturmechanismen (Technische Umsetzung die sich aus Anforderung ergibt, aus Anforderungen welche Technik ich brauche)
. Wir haben in der Analyse festgestellt, das wir alle Daten zu einem Antrag persistent speichern müssen (*SFA-2*). Hier haben wir zwei Möglichkeiten erwägt selbiges technisch Umzusetzen. Zwischen der Speicherung in einer SQL-Datenbank oder als Textdatei im CSV-Format, haben wir uns für eine SQL-Datenbank entschieden, da wir unsere Anträge gut relationell abbilden können und wir durch vorhandenes Vorwissen in SQL einfacher Abfragen in der Datenbank formulieren und testen können. Wir haben uns in der Implementierung für eine MySQL-Datenbank entschieden da sie uns eine gut dokumentierte Open-Source-Lösung bietet.

. Aus dem *SWFA-1* geht hervor, dass wir eine Nutzerverwaltung für die StuRa-Mitglieder benötigen. Hier haben wir die Möglichkeiten gesehen selbiges über direkt über Apache zu lösen und eine Access-Datei zu benutzen. Da wir keine weitere Registrierung benötigen und eine festgelegte Anzahl an Nutzerkonten haben, welche nicht auf einzelne Personen zugeschnitten sein muss, haben wir uns für die oben genannte Lösung entschieden.


== Abstraktion
=== *Typen / Daten die im Programm zur Laufzeit benötigt werden:*
* Antragseingaben: Umfasst alle Eingaben des Nutzers in das Formular die keine persönlichen Informationen sind
* Nutzerinformationen: Enthält alle Informationen zum Antragssteller (Umfasst Name, Vorname, E-Mail)
* Antragsvorgaben: Umfasst nicht änderbare Texte im Antrag sowie das Datum zum Antrag
* Sign-in: Informationen die einer Rolle den Login ermöglichen

=== *Services:*
* Antrag anlegen: Die Nutzereingaben werden an das PHP-Skript übergeben und an das Python-Skript weitergereicht. Mit den Nutzereingaben wird ein Insert-Befehl in der Datenbank ausgeführt um eine neue Zeile anzulegen.
* Antrag bearbeiten: Die gewünschten Änderungen des Antrags werden über einen Update-Befehl in der Datenbank geändert.
* Antragssatus ändern: Das Flag des Antrags in der Tabelle wird über einen Update-Befehl in der Datenbank geändert.
* Anmelden: Die eingegebenen Anmeldedaten werden, mit denen über einen Select-Befehl generierten, Daten aus der zum Login gespeicherten Daten abgeglichen und es wird ein entsprechendes Anmelden gewährleistet.

=== *Workflos:*

== Architektonischer Rahmen
* Kompatibilität zu den Webbrowsern wie Chrome, Firefox
* Verwendung von HTML und CSS für die Oberfläche 
* Javascript und falls nötig Python für die Mechaniken der Website
* Konfigurieren des Linux/Unix Servers/Webservers als Vorbild soll die Struktur der HTW Webserver dienen
* Generierung der Tagesordnung 

=== Architektonische Ansichten

==== Logische Sicht
In unserer logischen Schicht betrachten wir die einzelnen Komponenten des Systems. Der Webserver bildet die Grundlagen für die Darstellung der Webseite. Hier liegen alle HTML- sowie CSS- und Skriptdateien (Python, JavaScript, PHP). Über Skripte kommuniziert der Webserver mit der Datenbank indem Abfragen auf der Datenbank ausgeführt werden.

@startuml

node "Webserver" {
    [HTML]
    [Python]
    note left of [Python] : scripts select,insert,delete,update
    [CSS]
    note left of [CSS]
        predefined W3 
        and own stylesheet
    end note
    [JavaScript]
    [CSS] ..> [HTML] : styles
    [HTML] --> [Python] : calls
    
    [Python] --> finance : select,insert,delete,update
    [Python] --> universal : select,insert,delete,update
    [Python] --> advisory_member : select,insert,delete,update
    [Python] --> election : select,insert,delete,update
}

database "MySQL" {
    folder "finance" {
        [finance 1]
        [finance 2]
    }
    folder "universal" {
        [universal 1]
        [universal 2]
    }
    folder "advisory_member" {
        [advisory_member 1]
        [advisory_member 2]
    }
    folder "election" {
        [election 1]
        [election 2]
    }
}

@enduml

==== Pyhsische Sicht
Unsere Anwendung bildet ein Server-Client System ab. Im Fokus steht der Webserver der mehreren Clients die Funktionalitäten des Systems bereitstellen muss. Im Hintergrund steht der Datenbankserver der nur über Services angebunden ist.