= Projekt Plan: {project-name}
include::../_includes/default-attributes.inc.adoc[]


== Einleitung



Ziel des Projektes I3 Antragsmodul ist es eine browserbasierte Anwendung für den StuRa der HTW Dresden zu erstellen. Dabei soll das Tool auf die Abläufe des StuRas abgestimmt werden und auf Unix bzw. Linux laufen. Referatsleitungen des StuRas füllen Anträge aus, welchen durch das Antragsverwaltungstool ein Antragsdatum und eine Antragsnummer nach Systematik des StuRa zugewiesen wird. Das Tool soll daraus eine Tagesordnung für kommende Plenumssitzungen generieren.

== Projektorganisation



Unser Projektteam besteht aus den 8 folgenden Personen mit jeweiligen Zuständigkeitsbereichen:
[options="header"]
|===================================================
|Name           | Zuständigkeitsbereich | Backup
|Jacob Flaskamp | Implementierung / Test | Tien
|Richard Friese | Analyse | Amanda
|Andreas Gröber | Projektmanagement (in SE II) / Filler | Jasmin
|Jasmin Henn    | Projektmanagement | Andreas
|Ruben-David Kraus | Implementierung | Richard
|Richard Müller    | Entwurf | Ruben-David
|Duy Tien Nguyen   | Implementierung / Test | Jacob
|Amanda Wer Estrada| Analyse | Richard
|===================================================



Das Team trifft sich wöchentlich montags um 17:00 Uhr zu einer Telefonkonferenz auf Discord, in der neue Erkenntnisse, Auswertungen der Kundengespräche und Fragen ausgetauscht werden.
Kundenmeetings laufen ebenso über Discord in Form einer Telefonkonferenz ab. Unsere Ansprechpartner sind Axel Schiller und Liselotte Ruthe. An den Kundenmeetings nehmen 3 Mitglieder des Projektteams teil, welche sich abwechseln und die beiden Ansprechpartner. Termine für die Meetings werden auf die Kundenwünsche abgestimmt.

Außerdem wurden innerhalb des Teams kleinere Gruppen gebildet, die sich jeweils mit der Dokumentation der verschiedenen Zuständigkeitsbereiche beschäftigen:

[options="header"]
|===========================================================================
|Gruppenmitglieder | Aufgaben
|Amanda Wer Estrada, Richard Friese | Vision, Glossar, Use Case Model
|Jasmin Henn, Andreas Gröber | Projektplan, Risikoliste, Iteration Plan
|Richard Müller | Architektur-Notizbuch, unterstützt Teams bei: Use Case Model, Iteration Plan
|===========================================================================
== Projektpraktiken and Messwerte


Als Vorlage für die Projektdokumentation nutzt unser Team OpenUP. Zudem werden unsere Teammeetings protokolliert und anschließend von einer zweiten Person kontrolliert, um alle besprochenen Themen festzuhalten. Kundenmeetings werden aufgezeichnet, sodass alle Teammitglieder die Wünsche der Stakeholder verfolgen können.



== Projektmeilensteine und -ziele
Tabelle 3
[cols="1,20,8,4",options="header"]
|====================================================
|Iteration | Hauptziele | Meilensteine	| Erledigt bis
|I1        |Team kennenlernen, Rollenverteilung, Kommunikationswege festlegen, Kunden kennenlernen, Meetings mit Kunden durchführen, Vorstellung des Kundens erfassen und erste Konzepte entwerfen, Kundengespräche auswerten| 	1. Teammeeting, 1. Kundenmeeting, 2. Kundenmeeting| 20. Dezember 2020
|I2        | Erstellung der Projektdokumentationen für den Beleg (Projektplan, Risiko-Analyse), Auswertung der Kundengespräche vom Analyse-Team und Erfassung der Daten (Vision, Glossar, Use-Cases), Grundlegende Rahmenbedingungen und Vorstellungen für Implementierung festlegen| 3. Kundenmeeting, Projektdokumentationen bearbeiten| 10.Januar 2021
|I3 | Use-Cases mit dem Kunden besprechen und ggf. anpassen, Test Cases erstellen, 4. Kundenmeeting durchführen und auswerten, Team Implementierung beginnt seine Arbeit| 4. Kundenmeeting, Beginn Implementierung, Projektdokumentationen fertigstellen | 31. Januar 2021

|====================================================


== Bereitstellung der Software


Die fertige Software wird über den HTW Dresden Server laufen. Entweder über den StuRa oder das Rechenzentrum. Installation und Erstinbetriebnahme sind Projektbestandteile. Die Software wird während der Projektlaufzeit entwickelt und innerhalb dieser Zeit das letzte mal geupdatet.


== Gewonnene Erkenntnisse

Ergänzung folgt nach Beendigung des Projektes in SE 2