= Anwenderdokumentation: {project-name}
{localdatetime}
include::../../docs/_includes/default-attributes.inc.adoc[]
{mail}

== Ziel der Dokumentation
Ziel der Dokumentation sit es, den Anwender, wenn er nicht mehr weiter weiß, ein möglichst einfaches Dokument an die Hand zu geben damit er weiterarbeiten kann.

== Zweck und Funktionsumfang des Antragsverwaltungstools
=== Zweck
Das Antragsverwaltungstool soll dafür genutzt werden, Anträge an den StuRa stellen zu können und damit einhergehend eine Bearbeitung selbiger zu ermöglichen. 
Hier ist zwischen dem Stellen und Bearbeiten klar zu differenzieren.

==== Anträge stellen
Das Stellen von Anträgen soll für jederman, wie vom Studenten Rat gewünscht, von jedem möglich sein. Daher kann jede Person einen Antrag an den StuRa stellen. Dies umfasst Personen aus der Hochschle, aus dem StuRa, aus den Reihen der Professoren oder aber auch Personen oder Firmen, wobei letzteres eher seltener vorkommt. Hier lässt zwischen verschiedenen Anträgen unterscheiden, welche auf der Startseite des Antragsverwaltungstools aufgelistet und erklärt sind.

==== Anträge bearbeiten
Das Bearbeiten von Anträgen obligt nur den berechtigten Mitgliedern aus dem StuRa. Hierbei kann über die Angabe der Antragsnummer der Antrag in eine Maske ähnlich wie beim Antrag Stellen eingetragen und bearbeitet werden. Nach der Bearbeitung wird der Antrag abgeschickt und gespeichert.