= Betriebsdokumentation: {project-name}
{localdatetime}
include::../../docs/_includes/default-attributes.inc.adoc[]
{mail}

== Ziel der Dokumentation
Ziel der Dokumentation ist es den Administrator beim Einrichten, Konifgurieren, Innbetriebnhemen sowie Betreuen des Systems Rahmenbedingungen zu geben.

== Anforderungen an die Produktivumgebung
=== Systemvorraussetzungen

Zur Ausführung des Systems, in Hinblick auf Skalierbarkeit, wird benötigt:

==== Hardware

. Für den Server:
.. CPU mit 4 Kernen
.. 4 GB Arbeitsspeicher
.. 15 GB Festplattenspeicher
.. Internetanbindung mit mindestens 50 Mbit/s

==== Software

. Für den Server:
.. https://ubuntu.com/download/desktop[Ubuntu] (Version 20.04 LTS) oder https://www.debian.org/distrib/[Debian] (Version 10)
.. https://www.python.org/downloads/[Python3] bzw. Pip3
.. https://pypi.org/project/mysqlclient/[_mysqlclient_]
.. mindestens https://www.djangoproject.com/download/[Django] (Version 3.2.4 LTS)
.. https://httpd.apache.org/[Apache2]
.. https://ubuntu.com/download/desktop[Ubuntu] (Version 20.04 LTS) oder https://www.debian.org/distrib/[Debian] (Version 10)
.. https://dev.mysql.com/downloads/[MySQL Community Edition] (mindestens Version 8.0)

== Systemeinrichtung
=== Komponenten

Die Anwednung besteht im ganzen aus einer Django-Applikation welche sich in kleine Unterkomponenten gliedert (im Folgenden aufgelistet)
. HTML: Alle Seiten die die Applikation bereitstellt sind im Ordner _Templates_ zu finden.
. CSS: Die CSS-Dateien bilden das Styling für die HTML-Seiten und sind im Applikationsordner _Antragsverwaltungstool_ unter _static/css_ zu finden.
. PNG: In der Applikation befinden sich ebenfalls einzelne Bilder zum darstellen auf der Webseite, ebenfalls unter _static/png_
. JS: Es wird JavaScript benutzt um input Felder anzuzeigen oder zu verstecken. Zusätzlich um Texte einfach zu displayen.
. PY: Die Anwendung besteht zum Großteil aus Python-Dateien welche einerseits das MVC-Architekturprinzip wiederspiegeln (_views.py_, _models.py_) und andererseits die Funktionen des Frameworks bereitstellen. Wichtig ist auch hier die _settings.py_ indem für die Applikation spezifische Einstellungen festgelegt sind.
. MySQL-API-TReiber: Zum Betreiben wird ebenfalls ein Treiber zur Kommunikation mit der Datenbank benötigt. Hier wird https://pypi.org/project/mysqlclient/[_mysqlclient_] empfohlen.

=== Installation / Verzeichnisstruktur

Für die Installation ist nur Python und Django nötig sowie der Apache Webserver. Es kann entweder ein neues Django Projekt mit dem gleichen Namen erstellt werden, um dann die Dateien aus der Applikationen in das neue Projekt zu kopieren. Oder es wird der gesamte Ordner aus der fertigen Applikation kopiert. Hier ist es nötig die Python-Laufzeitumgebung entsprechend anzupassen, da in unserem Falle mit einem Python Virtual Environment gearbeitet wird. Die Verzeichnisstruktur wird beim Erstellen des Projektes automatisch erzeugt, Hier ist es nur notwendig die HTML-Unterordner in _Templates_ und den static-Ordner in den Root-Folder der Applikation zu verschieben. Auf dem Webserver wurden die Dateien im root Verzeichnis unter ~/Antragsverwaltungstool abgelegt.

=== Installation und Konfiguration von Django und Apache mit wsgi

Um unsere Server passent einzurichten und zu Konfigutieren sind wir diesem Guide gefolgt. https://www.digitalocean.com/community/tutorials/how-to-serve-django-applications-with-apache-and-mod_wsgi-on-ubuntu-14-04 nachdem wir unser Projekt angelegt hatten haben wir die Erstellten dateien des neuen Projektes mit unseren ausgetauscht und danach nochmals die Befehle
[source,linux terminal]
--
python3 ./manage.py makemigrations
python3 ./manage.py migrate
--

=== Konfiguration

Zur Konfiguration muss einerseits im der _settings.py_ die IP-Adresse des Datenbankservers angegeben werden mit einer zusätzlichen Angabe des MySQL-Treibers. Da der Server auf der gleichen Maschine läuft, wurde _localhost_ verwendet. Dafür muss in der Datenbank nur ein Nutzer für die Applikation angelegt werden. Damit die Applikation unter Apache2 lauffähig ist muss https://docs.djangoproject.com/en/3.2/howto/deployment/wsgi/modwsgi/[_WSGI_] verwendet werden. Dazu benötigt der Webserver Berechtigungen um die Dateien der Applikation ausführen und lesen zu können.



== Systembetreuung
=== Datensicherung und -wiederherstellung

Die Daten des Webservers können nach Notwendigkeit regelmäßig gesichert werden. Es ist systemseitige keine automatische Sicherung der Daten vorhanden.

=== Neustart des Servers
der Django Server ist in einer Screen session im Hintergrund und wird bei einem Reboot des Haubtsrevers *Nicht* Automatisch gestartet. Das muss Manuell gemacht werden.
Sollte man den Server Starten wollen muss man sich über ssh auf den Server einlogen und unter dem Benutzer "django_admin" folgende Befehle eingeben:
[source,linux terminal]
--
cd Antragsverwaltungstool
screen ./Serverstart.sh
--

Danach gelangt man in eine screen session. Um aus dieser Herauszukommen um den Prozess in den Hintergrund zu bringen muss man die Tastenkombination *STRG+A* danach *D* drücken dann kommt man zurück zu der Linux konsole und kann sich beispielsweise mit "exit" abmelden. 

Um den Serverprozess wieder in den Vordergrund zu bekommen benutzt man folgende befehle:
[source,linux terminal]
--
screen -ls
screen -r pts-2.antragsverwaltung 
--

:tip-caption: 💡
[TIP]
Sollte sich der Name der screen session ändern genügt es auch screen -r *TAB* zu drücken da der server gerade die einzige screen session sein sollte 
