= Testdokumentation: {project-name}
{localdatetime}
include::../../docs/_includes/default-attributes.inc.adoc[]
{mail}


include::../../docs/test/test_plan.adoc[]

== Testkonzept

Die wichtigsten zu testenden Komponenten waren die Weboberfläche (Front-End), die Datenbank und diverse Skripte zur Datenübermittlung und -verarbeitung.

Es wurden alle essenziellen Funktionen des Tools ausführlich getestet. Dazu gehört das Einreichen von Anträgen, die Suche und Anzeige von bereits eingereichten Anträgen und deren Bearbeitung.

Zum testen des use-cases "Antrag einreichen" wurde mittels der Antragsmaske verschiedene Testanträge in allen Antragskategorie eingereicht. Dabei wurde versucht diese mit fehlenden Daten einzureichen, um die Checks für leere Eingabefelder (z.B. Antragstitel, Name und E-Mail) zu testen.

Anschließend wurde über den Reiter "intern" das Suchen, das Anzeigen und die Bearbeitung von bereits eingereichten Anträgen getestet. Dazu wurde lediglich bei der Antragssuche eine Stelle ausgewählt und die Suche abgesendet.

Zum Testen der Anzeige und Bearbeitung von Anträgen wurden für verschiedene Anträge mittels der Antragsnummer (sowohl bereits vorhandene als auch nicht existierende) die Daten angefordert. Diese wurden dann mit den abgesendeten Daten abgeglichen. Zum Testen der Bearbeitungsfunktion wurden alle Daten eines Antrags bearbeitet und die Änderungen abgesendet. Danach wurden wieder die übermittelten Daten abgeglichen.

Ein Teil der Funktionstests ist bereits während der Implementierung durchgeführt worden. Ausführliche und tiefgehende Tests auf Fehlfunktionen und Verbesserungsmöglichkeiten sind dann durch das Team Test getätigt worden.

include::../../docs/test/test_script.adoc[] 

include::../../docs/test/test_log.adoc[]