# Generated by Django 3.2.4 on 2021-06-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0004_auto_20210614_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorymember',
            name='aenderung',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='advisorymember',
            name='anlagen',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='aenderung',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='anlagen',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='aenderung',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='anlagen',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='universall',
            name='aenderung',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='universall',
            name='anlagen',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
