# Generated by Django 3.2.4 on 2021-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0005_auto_20210624_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorymember',
            name='office',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='office',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='office',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='universall',
            name='office',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
