# Generated by Django 3.2.4 on 2021-06-24 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0006_auto_20210624_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('flag', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=25, null=True)),
                ('office', models.CharField(max_length=75, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.CharField(max_length=260, null=True)),
                ('reason', models.CharField(max_length=260, null=True)),
                ('suggestion', models.CharField(max_length=260, null=True)),
                ('anlagen', models.CharField(max_length=260, null=True)),
                ('aenderung', models.CharField(max_length=260, null=True)),
                ('mehrheit', models.CharField(max_length=25, null=True)),
                ('beschluss', models.CharField(max_length=25, null=True)),
                ('beschlusstext', models.CharField(max_length=25, null=True)),
                ('beschlussgrund', models.CharField(max_length=25, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
