# Generated by Django 3.2.4 on 2021-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0007_conduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislature', models.CharField(max_length=7)),
                ('session', models.IntegerField()),
                ('ongoing_number', models.IntegerField()),
            ],
            options={
                'ordering': ['ongoing_number'],
            },
        ),
    ]
