# Generated by Django 3.2.4 on 2021-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0008_numbercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbercount',
            name='number',
            field=models.CharField(unique=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='advisorymember',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='conduct',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='universall',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
