# Generated by Django 3.2.4 on 2021-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Antragsverwaltungstool', '0010_alter_numbercount_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbercount',
            name='id',
        ),
        migrations.AlterField(
            model_name='numbercount',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
